name: ci-cd-main

on:
  push:
    branches:
      - main

env:
  NETLIFY_SITE_ID: '008792a5-fe66-4d99-a842-9d8e44e76711'
  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN_PORTAIL }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Deploy site
      run: npx netlify-cli deploy --prod --dir .
      if: success()
